<?xml version='1.0' encoding="utf-8"?>
<!DOCTYPE sections SYSTEM "/dtd/book.dtd">

<!-- The content of this document is licensed under the CC-BY-SA license -->
<!-- See http://creativecommons.org/licenses/by-sa/1.0 -->

<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/proj/ja/hardened/selinux/hb-selinux-faq.xml,v 1.2 2006/02/17 18:57:22 idani Exp $ -->

<!-- Original revision: 1.2 -->
<!-- Translator: kobayashi -->

<sections>
<section><title>emergeをしているとSELinuxモジュールが消失する</title>
<subsection><title>「emergeを使っていたらこんなエラーがでました」</title>
<body>
<pre caption="Portageメッセージ">
!!! SELinux module not found. Please verify that it was installed.
</pre>
<p>
これはPortageのSELinuxモジュールが消失したか損傷したことを意味しています。
また、Pythonが、python-selinuxの再コンパイルが必要な新しいバージョンに更新されたのかもしれません。
dev-python/python-selinuxを再度emergeしてください。
パッケージがもしかすると正しくないラベルでマージされるかもしれないので、再ラベルが必要となるでしょう。
</p>
</body></subsection>
</section>

<section><title>カーネルの登録機能の失敗</title>
<subsection><title>「起動時にこんなカーネルエラーが出ました」</title>
<body>
<pre caption="カーネルメッセージ">
There is already a security framework initialized, register_security failed.
Failure registering capabilities with the kernel
selinux_register_security:  Registering secondary module capability
Capability LSM initialized
</pre>
<p>
これは、SELinuxが最初のモジュールとなっているので、Capability LSMモジュールを最初のモジュールとして登録できなかったことを意味します。
3番目のメッセージにはSELinuxを2番目のモジュールとして登録することを意味します。
このメッセージがでるのは正常です。
</p>
</body></subsection>
</section>

<section><title>ラベリング中の無効なコンテキスト</title>
<subsection><title>「再ラベリングをしていると、無効なコンテキストにより失敗します。」</title><body>
<pre caption="無効なコンテキストの例">
# make relabel
/usr/sbin/setfiles file_contexts/file_contexts `mount | awk '/(ext[23]| xfs).*rw/{print $3}'`
/usr/sbin/setfiles:  read 559 specifications
/usr/sbin/setfiles:  invalid context system_u:object_r:default_t on line number 39
/usr/sbin/setfiles:  invalid context system_u:object_r:urandom_device_t on line number 120
/usr/sbin/setfiles:  invalid context system_u:object_r:fonts_t on line number 377
/usr/sbin/setfiles:  invalid context system_u:object_r:fonts_t on line number 378
/usr/sbin/setfiles:  invalid context system_u:object_r:krb5_conf_t on line number 445
/usr/sbin/setfiles:  invalid context system_u:object_r:system_cron_spool_t on line number 478
/usr/sbin/setfiles:  invalid context system_u:object_r:system_cron_spool_t on line number 479
/usr/sbin/setfiles:  invalid context system_u:object_r:system_cron_spool_t on line number 492
/usr/sbin/setfiles:  invalid context system_u:object_r:system_cron_spool_t on line number 493
/usr/sbin/setfiles:  invalid context system_u:object_r:system_cron_spool_t on line number 494
Exiting after 10 errors.
make: *** [relabel] Error 1
</pre>
<p>
まず/selinuxを確実にマウントしてください。
selinuxfsがマウントされていなければ、setfilesはいかなるコンテキストも確認することができないので、全てのコンテキストが無効であると認識する原因となります。
もし/selinuxがマウントされているなら、もしかするとまだロードされていない新しいポリシーがあるのかもしれません。
その結果、コンテキストが無効とされるのです。
</p>
</body></subsection>
</section>


<!-- comment out since the demo machine is down for an indefinite period of time
<section><title>Gentoo SELinuxデモマシン</title>
<subsection><body>
<p>
このマシンはuser-mode Linuxやchroot環境で動作しておらず、SELinuxのアクセス制御の元にあります。
SELinuxのセキュリティを突破し、より高い特権を取得しない限り、マシンにpsybncやIRC BOTをインストールすることはできません。
</p>
</body></subsection>
</section>
-->
<!-- dont put anything below here, this demo machine faq should be the last one -->
</sections>
